# 1 Project setup

## import packages

In [1]:
import pandas as pd
import numpy as np
import os
import sys
os.chdir(r'C:\Users\merom\Documents\GitHub\collancer\investment-nsw\output')

# 2 Define functions

In [2]:
def share_calculator(data_set,columns,numerator_filter,denominator_filter,new_index,new_col):
    numerator = data_set.loc[numerator_filter,:].reset_index(drop=True)
    denominator = data_set.loc[denominator_filter,:].reset_index(drop=True)
    numerator = numerator.set_index(new_index)
    denominator = denominator.set_index(new_index)
    numerator[columns] = numerator[columns]/denominator[columns]
    for key,val in new_col.items(): numerator[key] = val
    return numerator[[key]+columns]

def region_cleaner(_table):
    _output = _table.copy()
    _output['region'] = _output['region'].astype(str)
    _output['region'] = _output['region'].apply(lambda x: x.replace('\xa0',' ').replace('\xad','').strip())
    _output['region'] = _output['region'].apply(lambda x: x.replace(', United States', ''))
    _output['region'] = _output['region'].apply(lambda x: x.replace(', Canada', ''))
    _output['region'] = _output['region'].apply(lambda x: x.replace(', Australia', ''))
    return _output

def year_summer(_table):
    _output = _table.copy()
    #years in data
    year_cols = [str(year) for year in range(2000,2025)]
    for y in year_cols:
        try:_output[y] = _output[y].apply(lambda x: float(x.replace(',','')))
        except: pass
    _output['2000_2005'] = _output[[str(year) for year in range(2000,2005)]].apply(lambda x: sum(x),axis=1)
    _output['2005_2010'] = _output[[str(year) for year in range(2005,2010)]].apply(lambda x: sum(x),axis=1)
    _output['2010_2015'] = _output[[str(year) for year in range(2010,2015)]].apply(lambda x: sum(x),axis=1)
    _output['2015_2020'] = _output[[str(year) for year in range(2015,2020)]].apply(lambda x: sum(x),axis=1)
    _output['2020_2025'] = _output[[str(year) for year in range(2020,2025)]].apply(lambda x: sum(x),axis=1)
    _output['2000_2024'] = _output[year_cols].apply(lambda x: sum(x),axis=1)
    return _output

In [3]:
year_cols = [str(x) for x in range(2000,2025)]

founder_data = pd.read_csv('master_data.csv').iloc[:,1:]
founder_data = region_cleaner(founder_data)
founder_data = year_summer(founder_data)


year_cols = year_cols+['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024',]
founder_data

,region,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,Founder Experience,Round,Industries,metric,2000_2005,2005_2010,2010_2015,2015_2020,2020_2025,2000_2024
0,United States,2940.0,1184.0,1227.0,1322.0,1707.0,2028.0,2521.0,3564.0,3803.0,...,All,All,All,rounds,8380.0,1.631400e+04,4.677500e+04,7.900000e+04,7.561500e+04,2.260840e+05
1,United Kingdom,129.0,118.0,108.0,123.0,160.0,226.0,267.0,381.0,412.0,...,All,All,All,rounds,638.0,1.675000e+03,6.097000e+03,1.509600e+04,1.571000e+04,3.921600e+04
2,New York,278.0,86.0,86.0,89.0,112.0,122.0,205.0,320.0,415.0,...,All,All,All,rounds,651.0,1.494000e+03,6.126000e+03,1.208200e+04,1.266500e+04,3.301800e+04
3,Canada,101.0,56.0,52.0,52.0,68.0,116.0,146.0,171.0,158.0,...,All,All,All,rounds,329.0,7.970000e+02,2.737000e+03,7.075000e+03,7.444000e+03,1.838200e+04
4,Singapore,7.0,3.0,3.0,2.0,4.0,6.0,11.0,26.0,28.0,...,All,All,All,rounds,19.0,9.800000e+01,6.540000e+02,2.500000e+03,3.415000e+03,6.686000e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,Pennsylvania,276000000.0,74000000.0,39400000.0,73400000.0,51400000.0,124000000.0,207000000.0,451000000.0,188000000.0,...,All,NOT SET,All,amount,514200000.0,1.072000e+09,1.433000e+09,3.232000e+09,7.476000e+09,1.372720e+10
332,Israel,109000000.0,122000000.0,67200000.0,31600000.0,57400000.0,129000000.0,151000000.0,346000000.0,307000000.0,...,All,NOT SET,All,amount,387200000.0,1.076000e+09,2.215000e+09,3.784000e+09,4.017000e+09,1.147920e+10
333,Victoria,64000000.0,0.0,0.0,0.0,0.0,2000000.0,0.0,0.0,85000000.0,...,All,NOT SET,All,amount,64000000.0,8.840000e+07,1.082000e+08,2.342000e+08,9.356000e+08,1.430400e+09
334,New Zealand,1000000.0,6500000.0,0.0,5900000.0,0.0,0.0,11400000.0,15000.0,1300000.0,...,All,NOT SET,All,amount,13400000.0,1.271500e+07,3.380000e+07,4.232000e+08,7.115000e+08,1.194615e+09
335,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,All,NOT SET,All,amount,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

## Average round size

In [37]:
round_t = founder_data.loc[(founder_data['Round']!='All')&
(founder_data['metric']!='amount')&
(founder_data['region'].isin(['United States','Canada','United Kingdom'])!=True),].groupby(
    ['Founder Experience','Round','Industries','Background','Degree','Gender']).sum()
round_t=round_t.loc[:,round_t.columns.isin(['region','metric'])==False]

fund_t = founder_data.loc[(founder_data['Round']!='All')&
(founder_data['metric']=='amount')&
(founder_data['region'].isin(['United States','Canada','United Kingdom'])!=True),].groupby(
    ['Founder Experience','Round','Industries','Background','Degree','Gender']).sum()

fund_t=fund_t.loc[:,fund_t.columns.isin(['region','metric'])==False]

(fund_t/round_t).to_csv('average_funding_per_round.csv')

                                                                          2000  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     3.274000e+08
                   NOT SET   All        All        All    All     4.067200e+09
                   SERIES A  All        All        All    All     1.839100e+09
                   SERIES B  All        All        All    All     1.906500e+09
                   SERIES C  All        All        All    All     5.680000e+08
                   SERIES D+ All        All        All    All     4.730000e+08

                                                                          2001  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     6.270000e+07
                   NOT SET   All        All        All    All     1.242304e+09
                   SERIES A  All        All        All    All     5.358000e+08
                   SERIES B  All        All        All    All     1.078900e+09
                   SERIES C  All        All        All    All     5.833000e+08
                   SERIES D+ All        All        All    All     1.970000e+08

                                                                         2002  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     120900000.0
                   NOT SET   All        All        All    All     642200000.0
                   SERIES A  All        All        All    All     254900000.0
                   SERIES B  All        All        All    All     328200000.0
                   SERIES C  All        All        All    All     252000000.0
                   SERIES D+ All        All        All    All     360000000.0

                                                                         2003  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     116200000.0
                   NOT SET   All        All        All    All     616300000.0
                   SERIES A  All        All        All    All     369000000.0
                   SERIES B  All        All        All    All     309500000.0
                   SERIES C  All        All        All    All     394500000.0
                   SERIES D+ All        All        All    All     240600000.0

                                                                         2004  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     109600000.0
                   NOT SET   All        All        All    All     714800000.0
                   SERIES A  All        All        All    All     521000000.0
                   SERIES B  All        All        All    All     484200000.0
                   SERIES C  All        All        All    All     295100000.0
                   SERIES D+ All        All        All    All     313300000.0

                                                                          2005  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     1.986000e+08
                   NOT SET   All        All        All    All     1.552500e+09
                   SERIES A  All        All        All    All     4.603000e+08
                   SERIES B  All        All        All    All     4.265000e+08
                   SERIES C  All        All        All    All     4.553000e+08
                   SERIES D+ All        All        All    All     4.610000e+08

                                                                          2006  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     1.839000e+08
                   NOT SET   All        All        All    All     1.475000e+09
                   SERIES A  All        All        All    All     8.320000e+08
                   SERIES B  All        All        All    All     7.132000e+08
                   SERIES C  All        All        All    All     5.260000e+08
                   SERIES D+ All        All        All    All     3.453000e+08

                                                                          2007  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     3.368000e+08
                   NOT SET   All        All        All    All     2.134915e+09
                   SERIES A  All        All        All    All     1.117000e+09
                   SERIES B  All        All        All    All     9.787000e+08
                   SERIES C  All        All        All    All     5.568000e+08
                   SERIES D+ All        All        All    All     8.900000e+08

                                                                          2008  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     3.275800e+08
                   NOT SET   All        All        All    All     2.600000e+09
                   SERIES A  All        All        All    All     1.056100e+09
                   SERIES B  All        All        All    All     8.800000e+08
                   SERIES C  All        All        All    All     6.242000e+08
                   SERIES D+ All        All        All    All     1.368800e+09

                                                                          2009  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     4.710000e+08
                   NOT SET   All        All        All    All     1.215100e+09
                   SERIES A  All        All        All    All     8.057000e+08
                   SERIES B  All        All        All    All     8.001000e+08
                   SERIES C  All        All        All    All     3.853000e+08
                   SERIES D+ All        All        All    All     5.065000e+08

                                                                  ...  \
Founder Experience Round     Industries Background Degree Gender  ...
All                Early     All        All        All    All     ...
                   NOT SET   All        All        All    All     ...
                   SERIES A  All        All        All    All     ...
                   SERIES B  All        All        All    All     ...
                   SERIES C  All        All        All    All     ...
                   SERIES D+ All        All        All    All     ...

                                                                          2021  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     4.650900e+09
                   NOT SET   All        All        All    All     3.537200e+10
                   SERIES A  All        All        All    All     1.708210e+10
                   SERIES B  All        All        All    All     1.750900e+10
                   SERIES C  All        All        All    All     1.645860e+10
                   SERIES D+ All        All        All    All     2.428900e+10

                                                                          2022  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     5.611000e+09
                   NOT SET   All        All        All    All     3.139300e+10
                   SERIES A  All        All        All    All     1.214370e+10
                   SERIES B  All        All        All    All     1.435200e+10
                   SERIES C  All        All        All    All     1.029900e+10
                   SERIES D+ All        All        All    All     9.017000e+09

                                                                          2023  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     3.935700e+09
                   NOT SET   All        All        All    All     1.645360e+10
                   SERIES A  All        All        All    All     7.935200e+09
                   SERIES B  All        All        All    All     6.209500e+09
                   SERIES C  All        All        All    All     4.843000e+09
                   SERIES D+ All        All        All    All     6.492000e+09

                                                                          2024  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     1.246600e+09
                   NOT SET   All        All        All    All     6.312500e+09
                   SERIES A  All        All        All    All     2.782100e+09
                   SERIES B  All        All        All    All     2.254500e+09
                   SERIES C  All        All        All    All     3.042600e+09
                   SERIES D+ All        All        All    All     3.797600e+09

                                                                     2000_2005  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     7.368000e+08
                   NOT SET   All        All        All    All     7.282804e+09
                   SERIES A  All        All        All    All     3.519800e+09
                   SERIES B  All        All        All    All     4.107300e+09
                   SERIES C  All        All        All    All     2.092900e+09
                   SERIES D+ All        All        All    All     1.583900e+09

                                                                     2005_2010  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     1.517880e+09
                   NOT SET   All        All        All    All     8.977515e+09
                   SERIES A  All        All        All    All     4.271100e+09
                   SERIES B  All        All        All    All     3.798500e+09
                   SERIES C  All        All        All    All     2.547600e+09
                   SERIES D+ All        All        All    All     3.571600e+09

                                                                     2010_2015  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     5.468000e+09
                   NOT SET   All        All        All    All     2.144840e+10
                   SERIES A  All        All        All    All     8.333000e+09
                   SERIES B  All        All        All    All     7.706600e+09
                   SERIES C  All        All        All    All     5.956800e+09
                   SERIES D+ All        All        All    All     6.868400e+09

                                                                     2015_2020  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     1.101390e+10
                   NOT SET   All        All        All    All     7.684030e+10
                   SERIES A  All        All        All    All     2.360540e+10
                   SERIES B  All        All        All    All     2.173680e+10
                   SERIES C  All        All        All    All     1.560200e+10
                   SERIES D+ All        All        All    All     2.922440e+10

                                                                     2020_2025  \
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     1.794470e+10
                   NOT SET   All        All        All    All     1.084751e+11
                   SERIES A  All        All        All    All     4.567370e+10
                   SERIES B  All        All        All    All     4.788830e+10
                   SERIES C  All        All        All    All     4.053220e+10
                   SERIES D+ All        All        All    All     5.097160e+10

                                                                     2000_2024
Founder Experience Round     Industries Background Degree Gender
All                Early     All        All        All    All     3.668128e+10
                   NOT SET   All        All        All    All     2.230241e+11
                   SERIES A  All        All        All    All     8.540300e+10
                   SERIES B  All        All        All    All     8.523750e+10
                   SERIES C  All        All        All    All     6.673150e+10
                   SERIES D+ All        All        All    All     9.221990e+10

[6 rows x 31 columns]

# 3 Founder analysis

### Founder filters

In [120]:
# Define filter set
total_rounds = (founder_data['Background'] == 'All')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'rounds')
women_rounds = (founder_data['Background'] == 'All')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'Women')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'rounds')
technical_rounds = (founder_data['Background'] == 'Technical background')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'rounds')
technical_phd_rounds = (founder_data['Background'] == 'Technical background')&(founder_data['Degree'] == 'PhD founder')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'rounds')
serial_rounds = (founder_data['Background'] == 'All')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'Serial')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'rounds')


total_funds = (founder_data['Background'] == 'All')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'amount')
women_funds = (founder_data['Background'] == 'All')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'Women')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'amount')
technical_funds = (founder_data['Background'] == 'Technical background')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'amount')
technical_phd_funds = (founder_data['Background'] == 'Technical background')&(founder_data['Degree'] == 'PhD founder')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'All')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'amount')
serial_funds = (founder_data['Background'] == 'All')&(founder_data['Degree'] == 'All')&(founder_data['Gender'] == 'All')\
    &(founder_data['Founder Experience'] == 'Serial')&(founder_data['Round'] == 'All')&(founder_data['metric'] == 'amount')

In [121]:
women_share_rounds = share_calculator(founder_data,year_cols,women_rounds,total_rounds,'region',{'measure_type':'Women share of rounds'})
women_share_funds = share_calculator(founder_data,year_cols,women_funds,total_funds,'region',{'measure_type':'Women share of funds'})

technical_founder_share_rounds = share_calculator(founder_data,year_cols,technical_rounds,total_rounds,'region',{'measure_type':'Technical founder share of rounds'})
technical_founder_share_funds = share_calculator(founder_data,year_cols,technical_funds,total_funds,'region',{'measure_type':'Technical founder share of funds'})

technical_phd_founder_share_rounds = share_calculator(founder_data,year_cols,technical_phd_rounds,total_rounds,'region',{'measure_type':'Technical PhD founder share of rounds'})
technical_phd_founder_share_funds = share_calculator(founder_data,year_cols,technical_phd_funds,total_funds,'region',{'measure_type':'Technical PhD founder share of funds'})

serial_founder_share_rounds = share_calculator(founder_data,year_cols,serial_rounds,total_rounds,'region',{'measure_type':'Serial Founder share of rounds'})
serial_founder_share_funds = share_calculator(founder_data,year_cols,serial_funds,total_funds,'region',{'measure_type':'Serial Founder share of funds'})

avg_women_fund = share_calculator(founder_data,year_cols,women_funds,women_rounds,'region',{'measure_type':'Women avg. fund'})
avg_total_fund = share_calculator(founder_data,year_cols,total_funds,total_rounds,'region',{'measure_type':'All avg. fund'})
avg_total_technical_founder = share_calculator(founder_data,year_cols,technical_funds,technical_rounds,'region',{'measure_type':'Technical avg. fund'})
avg_total_technical_phd_founder = share_calculator(founder_data,year_cols,technical_phd_funds,technical_phd_rounds,'region',{'measure_type':'Technical PhD avg. fund'})

In [106]:
pd.concat([women_share_rounds,technical_founder_share_rounds,technical_phd_founder_share_rounds,serial_founder_share_rounds
           ,women_share_funds,technical_founder_share_funds,technical_phd_founder_share_funds,serial_founder_share_funds
           ,avg_total_fund,avg_women_fund,avg_total_technical_founder,avg_total_technical_phd_founder],axis=0).to_csv('founder_summary_stats.csv')

In [107]:
founder_data[total_funds].to_csv('total_capital.csv')

In [129]:
founder_data[total_funds][['region','2000_2024']].to_csv('2000_2024_vc_by_region.csv')

# 4 NSW Capital

In [108]:
nsw_filter = (founder_data['region'].isin(['New South Wales','Victoria','Australia']))&(founder_data['Round']!='All')&(founder_data['metric']=='amount')
founder_data[nsw_filter].to_csv('Australian funding by stage.csv')

all_filter = (founder_data['region'].isin(['New South Wales','Victoria','Australia'])==False)&(founder_data['Round']!='All')&(founder_data['metric']=='amount')
founder_data[all_filter].groupby('Round')[year_cols].sum().to_csv('Global funding by stage.csv')

# 5 Foreign investment

## Load industry data

In [109]:
industry_data = pd.read_csv('master_data_industry2.csv').iloc[:,1:]

mapping = pd.read_csv('industry_mappings2.csv')
#summarise years
industry_data = year_summer(industry_data)
industry_data['Industries']=industry_data['Industries'].apply(lambda x: x.strip()) 
#year_cols = year_cols+['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024',]

industry_data = industry_data.merge(mapping,how='left',left_on='Industries', right_on='dealroom_subindustry')

## industry filters

In [110]:
industry_data.Investor.unique()

array(['All', 'Australia', 'United States', 'Canada', 'Israel',
       'Singapore', 'New Zealand', 'United Kingdom'], dtype=object)

In [111]:
all_investors_filter = (industry_data.Investor=='All')&(industry_data.metric=='amount')&(industry_data.Round=='All')
domestic_investors_filter = (
    (((industry_data.Investor=='Australia')&(industry_data.region.isin(['Australia','New South Wales','Victoria'])))|
     ((industry_data.Investor=='Israel')&(industry_data.region.isin(['Israel'])))|
     ((industry_data.Investor=='Canada')&(industry_data.region.isin(['Canada','Ontario'])))|
     ((industry_data.Investor=='New Zealand')&(industry_data.region.isin(['New Zealand'])))|
     ((industry_data.Investor=='United Kingdom')&(industry_data.region.isin(['United Kingdom'])))|
     ((industry_data.Investor=='Singapore')&(industry_data.region.isin(['Singapore'])))|
     ((industry_data.Investor=='United States')&(industry_data.region.isin(['United States','Pennsylvania','Texas','New York'])))
     ) & (industry_data.metric=='amount') & (industry_data.Investor!='All')&(industry_data.Round=='All'))

all_investors = industry_data[all_investors_filter].groupby('region').sum()[year_cols]
domestic_investors = industry_data[domestic_investors_filter].groupby('region').sum()[year_cols]

foreign_share = 1-domestic_investors/all_investors
foreign_share['measure_type'] = 'Foreign share of VC investment'
foreign_share[['measure_type']+year_cols].to_csv('foreign_investment_share.csv')

In [112]:
year_cols

['2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2000_2005',
 '2005_2010',
 '2010_2015',
 '2015_2020',
 '2020_2025',
 '2000_2024']

In [113]:
all_investors = industry_data[all_investors_filter&(industry_data.region == 'New South Wales')&(industry_data.Round=='All')].groupby(['region','custom_mappings']).sum()[year_cols]
domestic_investors = industry_data[domestic_investors_filter&(industry_data.region == 'New South Wales')&(industry_data.Round=='All')].groupby(['region','custom_mappings']).sum()[year_cols]
foreign_share_industry_nsw = 1-domestic_investors/all_investors
foreign_share_industry_nsw['total'] = all_investors['2000_2024']
foreign_share_industry_nsw['domestic_total'] = foreign_share_industry_nsw['total']*(1-foreign_share_industry_nsw['2000_2024'])
foreign_share_industry_nsw['foreign_total'] = foreign_share_industry_nsw['total']*(foreign_share_industry_nsw['2000_2024'])
foreign_share_industry_nsw.to_csv('nsw_foreign_share_industry.csv')

In [116]:
nsw_industries = industry_data[(industry_data.region == 'New South Wales')&(industry_data.Investor == 'All')&(industry_data.Round=='All')&(industry_data.metric=='amount')].groupby(['custom_mappings']).sum()[year_cols]
all_industries = industry_data[(industry_data.region == 'All')&(industry_data.Investor == 'All')&(industry_data.Round=='All')&(industry_data.metric=='amount')].groupby(['custom_mappings']).sum()[year_cols]

nsw_total = nsw_industries[year_cols].sum(axis=0)
all_total =  all_industries[year_cols].sum(axis=0)
nsw_industries[year_cols] = nsw_industries[year_cols].apply(lambda x: x/nsw_total,axis=1)
all_industries[year_cols] = all_industries[year_cols].apply(lambda x: x/all_total,axis=1)

all_industries = all_industries[['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024']]
nsw_industries = nsw_industries[['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024']]

industry_shares = pd.merge(all_industries,nsw_industries,how='inner',left_index=True,right_index=True)
rename_cols = {}
for c in industry_shares.columns:rename_cols[c] = c.replace('_x','Global').replace('_y','NSW')

industry_shares = industry_shares.rename(columns=rename_cols)
industry_shares.to_csv('industry_shares.csv')

In [115]:
nsw_industries = industry_data[(industry_data.region == 'New South Wales')&(industry_data.Investor == 'All')&(industry_data.metric=='amount')&(industry_data.Round=='All')].groupby(['custom_mappings']).sum()[year_cols]
all_industries = industry_data[(industry_data.region == 'All')&(industry_data.Investor == 'All')&(industry_data.metric=='amount')&(industry_data.Round=='All')].groupby(['custom_mappings']).sum()[year_cols]

nsw_total = nsw_industries[year_cols].sum(axis=0)
all_total =  all_industries[year_cols].sum(axis=0)

all_industries = all_industries[['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024']]
nsw_industries = nsw_industries[['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024']]

industry_shares = pd.merge(all_industries,nsw_industries,how='inner',left_index=True,right_index=True)
rename_cols = {}
for c in industry_shares.columns:rename_cols[c] = c.replace('_x','Global').replace('_y','NSW')

industry_shares = industry_shares.rename(columns=rename_cols)
industry_shares.to_csv('industry_totals.csv')

In [ ]:
industry_data[(industry_data.region == 'All')&(industry_data.Investor == 'All')&(industry_data.metric=='amount')&(industry_data.Round=='All')]

# 5 Technologies

In [36]:
technology_data = pd.read_csv('technologies_data.csv').iloc[:-1,1:]
technology_data = region_cleaner(technology_data)
technology_data = year_summer(technology_data)

year_cols = year_cols+['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024',]

In [37]:
technology_data['region'][technology_data['region'].isin(['Europe','North America','South America','Oceania','Asia','Africa'])] = 'World'
technology_data = technology_data[technology_data['region'].isin(['World','New South Wales'])]

C:\Users\merom\AppData\Local\Temp\ipykernel_18604\1885181580.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  technology_data['region'][technology_data['region'].isin(['Europe','North America','South America','Oceania','Asia','Africa'])] = 'World'
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\1885181580.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  technology_data['region'][technology_data['region'].isin(['Europe','North America','South America','Oceania','Asia','Africa'])] = 'World'

In [38]:
total_investment = founder_data[total_funds].set_index('region')
tech_filter = technology_data.metric=='amount'
tech_master = pd.DataFrame()
for i in ['Quantum','AI','Deep Tech']:
    temp_table = technology_data[tech_filter&(technology_data.Industries==i)].set_index('region')[year_cols]/total_investment[year_cols]
    temp_table['Industries']=i
    tech_master = pd.concat([tech_master,temp_table],axis=0)
tech_master.to_csv('hih_tech_region.csv')

In [40]:
tech_master = technology_data.groupby(['region','Industries']).sum()[year_cols]
for i in tech_master.index:
    if (i[1]!='All'):
        if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
        if (i[0]=='World'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('World','All'),:]
tech_master.to_csv('global_tech_investment_share.csv')

C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0027624309392265192' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.008482142857142856' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003153153153153153' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0007277840269966254' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003022017556482947' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003022017556482947' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003022017556482947' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003022017556482947' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003022017556482947' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.044753086419753084' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.040641711229946524' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.011538461538461539' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.012048192771084338' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.012048192771084338' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.012048192771084338' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.012048192771084338' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.012048192771084338' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.01639344262295082' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.18032786885245902' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5394190871369294' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.08393632416787265' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.16619718309859155' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.07838983050847458' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02531544094224071' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02531544094224071' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02531544094224071' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02531544094224071' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02531544094224071' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='New South Wales'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('New South Wales','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00757274745822134' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='World'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('World','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.006621654458985663' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='World'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('World','All'),:]
C:\Users\merom\AppData\Local\Temp\ipykernel_18604\2846285305.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.009210446175397754' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  if (i[0]=='World'): tech_master.loc[i,:]=tech_master.loc[i,:]/tech_master.loc[('World','All'),:]

In [33]:
tech_master

                                            2000          2001          2002  \
region          Industries
New South Wales 3D Technology       0.000000e+00  0.000000e+00  0.000000e+00
                AI                  0.000000e+00  0.000000e+00  0.000000e+00
                All                 2.920000e+07  1.900000e+03  6.000000e+06
                Autonomous Sensors  0.000000e+00  0.000000e+00  0.000000e+00
                Big Data            0.000000e+00  0.000000e+00  0.000000e+00
                Blockchain          0.000000e+00  0.000000e+00  0.000000e+00
                Deep Tech           0.000000e+00  0.000000e+00  0.000000e+00
                Hardware            0.000000e+00  0.000000e+00  0.000000e+00
                IoT                 0.000000e+00  0.000000e+00  0.000000e+00
                Machine Learning    0.000000e+00  0.000000e+00  0.000000e+00
                Mobile Apps         0.000000e+00  0.000000e+00  0.000000e+00
                Nano-technology     0.000000e+00  0.000000e+00  0.000000e+00
                Quantum             0.000000e+00  0.000000e+00  0.000000e+00
                VR/AR               0.000000e+00  0.000000e+00  0.000000e+00
World           3D Technology       7.572747e-03  6.621654e-03  9.210446e-03
                AI                  1.583109e-02  3.693547e-02  3.597556e-02
                All                 5.134200e+10  2.304560e+10  1.477670e+10
                Autonomous Sensors  1.402361e-04  4.816538e-04  0.000000e+00
                Big Data            1.312376e-02  1.445395e-02  2.464014e-02
                Blockchain          3.624713e-03  3.953032e-03  3.160381e-03
                Deep Tech           4.703578e-02  1.730005e-01  1.217593e-01
                Hardware            6.222196e-02  1.905933e-01  1.336902e-01
                IoT                 2.015114e-02  1.078731e-02  4.270236e-03
                Machine Learning    7.526002e-03  1.657583e-02  1.258738e-02
                Mobile Apps         6.115851e-03  1.484014e-02  3.234822e-03
                Nano-technology     2.082330e-03  4.512792e-03  7.775755e-03
                Quantum             0.000000e+00  1.102163e-03  4.182260e-03
                VR/AR               1.694357e-03  3.592877e-03  1.482063e-03

                                            2003          2004          2005  \
region          Industries
New South Wales 3D Technology       0.000000e+00  0.000000e+00  0.000000e+00
                AI                  0.000000e+00  0.000000e+00  0.000000e+00
                All                 6.100000e+06  6.100000e+06  2.410000e+07
                Autonomous Sensors  0.000000e+00  0.000000e+00  0.000000e+00
                Big Data            0.000000e+00  0.000000e+00  0.000000e+00
                Blockchain          0.000000e+00  0.000000e+00  0.000000e+00
                Deep Tech           0.000000e+00  0.000000e+00  0.000000e+00
                Hardware            1.639344e-02  1.803279e-01  5.394191e-01
                IoT                 0.000000e+00  0.000000e+00  0.000000e+00
                Machine Learning    0.000000e+00  0.000000e+00  0.000000e+00
                Mobile Apps         0.000000e+00  0.000000e+00  0.000000e+00
                Nano-technology     0.000000e+00  0.000000e+00  0.000000e+00
                Quantum             0.000000e+00  0.000000e+00  0.000000e+00
                VR/AR               0.000000e+00  0.000000e+00  0.000000e+00
World           3D Technology       5.881679e-03  6.936207e-03  8.867846e-03
                AI                  3.088387e-02  4.633117e-02  3.301515e-02
                All                 1.484270e+10  1.930450e+10  2.361340e+10
                Autonomous Sensors  1.347464e-04  1.013924e-03  1.710893e-03
                Big Data            2.939492e-02  4.110959e-02  4.225567e-02
                Blockchain          1.307040e-03  6.164366e-04  1.995901e-03
                Deep Tech           1.752377e-01  1.007537e-01  1.051733e-01
                Hardware            1.870819e-01  1.122588e-01  1.297568e-01
                IoT                 7.229143e-03  8.153539e-03  1.285711e-02
                Machine Learning    1.455935e-02  2.138362e-02  1.572836e-02
                Mobile Apps         5.487816e-03  3.118444e-03  1.179839e-02
                Nano-technology     9.614154e-03  4.071590e-03  1.040934e-02
                Quantum             5.591975e-03  1.626564e-03  3.831723e-03
                VR/AR               2.641029e-03  3.289388e-03  3.163458e-03

                                            2006          2007          2008  \
region          Industries
New South Wales 3D Technology       0.000000e+00  0.000000e+00  0.000000e+00
                AI                  0.000000e+00  0.000000e+00  0.000000e+00
                All                 6.910000e+07  3.550000e+07  6.480000e+07
                Autonomous Sensors  0.000000e+00  0.000000e+00  0.000000e+00
                Big Data            0.000000e+00  0.000000e+00  4.475309e-02
                Blockchain          0.000000e+00  0.000000e+00  0.000000e+00
                Deep Tech           0.000000e+00  0.000000e+00  4.475309e-02
                Hardware            8.393632e-02  1.661972e-01  7.716049e-02
                IoT                 0.000000e+00  0.000000e+00  0.000000e+00
                Machine Learning    0.000000e+00  0.000000e+00  4.475309e-02
                Mobile Apps         0.000000e+00  0.000000e+00  0.000000e+00
                Nano-technology     0.000000e+00  0.000000e+00  0.000000e+00
                Quantum             0.000000e+00  0.000000e+00  0.000000e+00
                VR/AR               0.000000e+00  0.000000e+00  0.000000e+00
World           3D Technology       7.483951e-03  9.243217e-03  1.572198e-02
                AI                  4.529813e-02  5.367896e-02  4.099092e-02
                All                 2.981580e+10  4.392410e+10  4.395120e+10
                Autonomous Sensors  4.158869e-03  6.313163e-03  1.563097e-03
                Big Data            3.965683e-02  5.173014e-02  3.925263e-02
                Blockchain          2.877669e-03  1.707491e-03  1.115328e-03
                Deep Tech           1.171392e-01  1.041114e-01  8.081918e-02
                Hardware            1.071445e-01  1.027614e-01  9.995176e-02
                IoT                 1.643089e-02  1.787857e-02  1.507581e-02
                Machine Learning    2.053945e-02  1.804476e-02  1.916216e-02
                Mobile Apps         1.010873e-02  1.227344e-02  1.168569e-02
                Nano-technology     1.308367e-02  9.026935e-03  5.883798e-03
                Quantum             1.348278e-03  0.000000e+00  8.190903e-04
                VR/AR               7.900174e-03  4.557862e-03  7.826863e-03

                                            2009  ...     2010_2015  \
region          Industries                        ...
New South Wales 3D Technology       0.000000e+00  ...  3.022018e-03
                AI                  0.000000e+00  ...  1.784429e-02
                All                 4.720000e+07  ...  6.949000e+08
                Autonomous Sensors  0.000000e+00  ...  0.000000e+00
                Big Data            0.000000e+00  ...  8.713484e-03
                Blockchain          0.000000e+00  ...  1.657246e-02
                Deep Tech           0.000000e+00  ...  3.763131e-02
                Hardware            7.838983e-02  ...  1.467837e-02
                IoT                 0.000000e+00  ...  5.413729e-03
                Machine Learning    0.000000e+00  ...  7.306951e-03
                Mobile Apps         0.000000e+00  ...  2.814793e-02
                Nano-technology     0.000000e+00  ...  0.000000e+00
                Quantum             0.000000e+00  ...  0.000000e+00
                VR/AR               0.000000e+00  ...  0.000000e+00
World           3D Technology       1.057044e-02  ...  1.328157e-02
                AI                  6.356269e-02  ...  1.003256e-01
                All                 3.141780e+10  ...  3.781220e+11
                Autonomous Sensors  2.985569e-03  ...  6.224934e-03
                Big Data            5.181776e-02  ...  8.050269e-02
                Blockchain          8.404471e-04  ...  4.398541e-03
                Deep Tech           1.025215e-01  ...  1.085903e-01
                Hardware            1.002489e-01  ...  8.612695e-02
                IoT                 1.870277e-02  ...  2.575211e-02
                Machine Learning    2.117908e-02  ...  4.169119e-02
                Mobile Apps         7.448962e-03  ...  3.981350e-02
                Nano-technology     1.490556e-02  ...  1.940263e-02
                Quantum             4.456073e-04  ...  1.169728e-03
                VR/AR               8.406063e-03  ...  2.168270e-02

                                       2015_2020     2020_2025     2000_2024  \
region          Industries
New South Wales 3D Technology       1.221130e-02  8.973238e-03  9.399748e-03
                AI                  1.003931e-01  1.044107e-01  9.737154e-02
                All                 4.070000e+09  1.008900e+10  1.514200e+10
                Autonomous Sensors  1.179290e-02  1.068490e-02  1.028907e-02
                Big Data            7.300737e-03  1.527406e-02  1.273075e-02
                Blockchain          3.320639e-02  4.933095e-02  4.255489e-02
                Deep Tech           6.914005e-02  1.488453e-01  1.196770e-01
                Hardware            5.285012e-02  6.744970e-02  6.210539e-02
                IoT                 1.948403e-02  2.289622e-02  2.074111e-02
                Machine Learning    3.950860e-02  3.334265e-02  3.336227e-02
                Mobile Apps         9.791155e-02  7.782734e-02  7.946505e-02
                Nano-technology     2.221376e-03  2.755476e-03  2.433034e-03
                Quantum             3.375921e-02  2.285658e-02  2.430326e-02
                VR/AR               2.929484e-03  1.963723e-03  2.095826e-03
World           3D Technology       1.355185e-02  9.894620e-03  1.134800e-02
                AI                  2.061340e-01  2.827353e-01  2.233118e-01
                All                 1.307799e+12  2.073956e+12  4.055911e+12
                Autonomous Sensors  2.352056e-02  2.639739e-02  2.182125e-02
                Big Data            9.110342e-02  7.264963e-02  7.659523e-02
                Blockchain          1.359197e-02  3.945431e-02  2.512476e-02
                Deep Tech           1.474575e-01  2.023168e-01  1.685369e-01
                Hardware            7.772294e-02  1.092117e-01  9.702728e-02
                IoT                 3.353732e-02  2.767148e-02  2.845894e-02
                Machine Learning    7.883260e-02  8.748493e-02  7.524050e-02
                Mobile Apps         8.497453e-02  9.419785e-02  7.994711e-02
                Nano-technology     2.506862e-02  1.528418e-02  1.827614e-02
                Quantum             1.716349e-03  5.507639e-03  3.573013e-03
                VR/AR               2.089896e-02  1.296441e-02  1.573775e-02

                                       2000_2005     2005_2010     2010_2015  \
region          Industries
New South Wales 3D Technology       0.000000e+00  0.000000e+00  3.022018e-03
                AI                  0.000000e+00  0.000000e+00  1.784429e-02
                All                 4.740190e+07  2.407000e+08  6.949000e+08
                Autonomous Sensors  0.000000e+00  0.000000e+00  0.000000e+00
                Big Data            0.000000e+00  1.204819e-02  8.713484e-03
                Blockchain          0.000000e+00  0.000000e+00  1.657246e-02
                Deep Tech           0.000000e+00  1.204819e-02  3.763131e-02
                Hardware            2.531544e-02  1.387619e-01  1.467837e-02
                IoT                 0.000000e+00  0.000000e+00  5.413729e-03
                Machine Learning    0.000000e+00  1.204819e-02  7.306951e-03
                Mobile Apps         0.000000e+00  0.000000e+00  2.814793e-02
                Nano-technology     0.000000e+00  0.000000e+00  0.000000e+00
                Quantum             0.000000e+00  0.000000e+00  0.000000e+00
                VR/AR               0.000000e+00  0.000000e+00  0.000000e+00
World           3D Technology       7.288047e-03  1.077823e-02  1.328157e-02
                AI                  2.877590e-02  4.797643e-02  1.003256e-01
                All                 1.233115e+11  1.727223e+11  3.781220e+11
                Autonomous Sensors  3.233543e-04  3.498101e-03  6.224934e-03
                Big Data            2.109211e-02  4.519162e-02  8.050269e-02
                Blockchain          2.880510e-03  1.640524e-03  4.398541e-03
                Deep Tech           1.033724e-01  1.002893e-01  1.085903e-01
                Hardware            1.176398e-01  1.060367e-01  8.612695e-02
                IoT                 1.306447e-02  1.637889e-02  2.575211e-02
                Machine Learning    1.283984e-02  1.901318e-02  4.169119e-02
                Mobile Apps         6.856246e-03  1.080770e-02  3.981350e-02
                Nano-technology     4.436821e-03  1.018571e-02  1.940263e-02
                Quantum             1.634884e-03  1.046072e-03  1.169728e-03
                VR/AR               2.387382e-03  6.476002e-03  2.168270e-02

                                       2015_2020     2020_2025     2000_2024
region          Industries
New South Wales 3D Technology       1.221130e-02  8.973238e-03  9.399748e-03
                AI                  1.003931e-01  1.044107e-01  9.737154e-02
                All                 4.070000e+09  1.008900e+10  1.514200e+10
                Autonomous Sensors  1.179290e-02  1.068490e-02  1.028907e-02
                Big Data            7.300737e-03  1.527406e-02  1.273075e-02
                Blockchain          3.320639e-02  4.933095e-02  4.255489e-02
                Deep Tech           6.914005e-02  1.488453e-01  1.196770e-01
                Hardware            5.285012e-02  6.744970e-02  6.210539e-02
                IoT                 1.948403e-02  2.289622e-02  2.074111e-02
                Machine Learning    3.950860e-02  3.334265e-02  3.336227e-02
                Mobile Apps         9.791155e-02  7.782734e-02  7.946505e-02
                Nano-technology     2.221376e-03  2.755476e-03  2.433034e-03
                Quantum             3.375921e-02  2.285658e-02  2.430326e-02
                VR/AR               2.929484e-03  1.963723e-03  2.095826e-03
World           3D Technology       1.355185e-02  9.894620e-03  1.134800e-02
                AI                  2.061340e-01  2.827353e-01  2.233118e-01
                All                 1.307799e+12  2.073956e+12  4.055911e+12
                Autonomous Sensors  2.352056e-02  2.639739e-02  2.182125e-02
                Big Data            9.110342e-02  7.264963e-02  7.659523e-02
                Blockchain          1.359197e-02  3.945431e-02  2.512476e-02
                Deep Tech           1.474575e-01  2.023168e-01  1.685369e-01
                Hardware            7.772294e-02  1.092117e-01  9.702728e-02
                IoT                 3.353732e-02  2.767148e-02  2.845894e-02
                Machine Learning    7.883260e-02  8.748493e-02  7.524050e-02
                Mobile Apps         8.497453e-02  9.419785e-02  7.994711e-02
                Nano-technology     2.506862e-02  1.528418e-02  1.827614e-02
                Quantum             1.716349e-03  5.507639e-03  3.573013e-03
                VR/AR               2.089896e-02  1.296441e-02  1.573775e-02

[28 rows x 43 columns]

# Public data

In [536]:
technology_data = pd.read_csv('public_funds_data.csv').iloc[:-1,1:]
technology_data = region_cleaner(technology_data)
technology_data = year_summer(technology_data)
year_cols = year_cols+['2000_2005','2005_2010','2010_2015','2015_2020','2020_2025','2000_2024',]

In [524]:
(technology_data[technology_data.metric=='amount'].set_index('region')[year_cols]/total_investment[year_cols]).to_csv('public_investment.csv')